#!/usr/bin/env bash
#
# Fail when languages/post-voice.pot no longer matches the strings in the source.
#
# The spec asks for the .pot to be generated by a script in CI. Regenerating it
# there and committing the result is not an option — CI does not push — so this
# checks the committed file instead: it regenerates into a scratch copy and
# compares. A translatable string added without running `npm run i18n:pot` is a
# string no translator ever sees, and nothing else in the pipeline notices.
#
# The comparison is on translatable content only — msgid, msgid_plural, msgctxt
# — not a plain diff. `wp i18n make-pot` stamps POT-Creation-Date on every run
# and records source line numbers, so a byte comparison would fail on any commit
# that shifts a line, and pass only by accident.

set -euo pipefail

cd "$(dirname "$0")/.."

committed="languages/post-voice.pot"
generated="languages/.pot-check.pot"

trap 'rm -f "$generated"' EXIT

npm run build:dev

# Same invocation as `npm run i18n:pot`, writing somewhere disposable. The path
# is relative to --env-cwd, which is the plugin root inside the container.
npx wp-env run cli --env-cwd=wp-content/plugins/post-voice \
	wp i18n make-pot . "$generated" \
	--include=post-voice.php,shared/php,features/narration/php,features/pronunciation/php,features/player-style/php,build/narration-editor.js,build/narration-player.js,build/dictionary-admin.js,build/player-style-admin.js,build/models-admin.js

strings_in() {
	grep -E '^(msgid|msgid_plural|msgctxt) ' "$1" | sort
}

if ! diff -u <( strings_in "$committed" ) <( strings_in "$generated" ); then
	echo
	echo "languages/post-voice.pot is out of date (- committed, + source)."
	echo "Run 'npm run i18n:pot' and commit the result."
	exit 1
fi

echo "languages/post-voice.pot is current."
